blocks:
  - name: step
    from: sources
    type: step
    value_before: [[0]]
    value_after: [[8.0]]
    start_time: 0.4
  - name: error
    from: operators
    type: sum
    num_inputs: 2
    signs: [1.0, -1.0]
  - name: pid
    from: controllers
    type: pid
    controller: PI
    Kp: [[0.5]]
    Ki: [[0.8]]
  - name: sofa
    from: systems
    type: sofa_plant
    scene_file: /home/aalessan/Documents/Perso/code/pySimBlocks/examples/generate/sofa/Finger.py
    input_keys: [cable]
    output_keys: [tip, measure]
connections:
  - [step.out, error.in1]
  - [error.out, pid.e]
  - [pid.u, sofa.cable]
  - [sofa.measure, error.in2]
simulation:
  dt: 0.01
  T: 5.0
  log:
    - step.outputs.out
    - sofa.outputs.measure
    - pid.outputs.u
plot:
  - title: Outputs
    log:
      - step.outputs.out
      - sofa.outputs.measure
  - title: Command
    log:
      - pid.outputs.u
