simulation:
  dt: 0.01
  T: 3.0
  solver: fixed

logging:
  - ref.outputs.out
  - plant.outputs.y
  - pid.outputs.u

blocks:
  ref:
    value_before: [[0.0]]
    value_after: [[1.0]]
    start_time: 0.5

  error:
    num_inputs: 2
    signs: [1., -1]

  pid:
    controller: PI
    Kp: [[2.0]]
    Ki: [[1.0]]

  plant:
    A: [[0.95]]
    B: [[0.5]]
    C: [[1.0]]
    x0: [[0.0]]
