simulation:
  dt: 0.01
  T: 2.0
  t0: 0.0
  solver: fixed

logging:
  - ref.outputs.out
  - plant.outputs.y

blocks:
  ref:
    value_before: [[0.0]]
    value_after: [[1.0]]
    start_time: 0.5

  plant:
    A: [[0.9]]
    B: [[1.0]]
    C: [[1.0]]
    x0: [[0.0]]
