schema_version: 1
project:
  name: algebraic_function
  metadata:
    created_by: pySimBlocks
    created_at: '2026-02-18T00:00:00Z'
simulation:
  dt: 0.1
  T: 10.0
  solver: fixed
  logging:
  - Algebraic Function.outputs.y1
  - Algebraic Function.outputs.y2
  - Constant.outputs.out
  - Step.outputs.out
  plots: []
diagram:
  blocks:
  - name: Algebraic Function
    category: operators
    type: algebraic_function
    parameters:
      file_path: g.py
      function_name: g
      input_keys:
      - u1
      - u2
      output_keys:
      - y1
      - y2
  - name: Constant
    category: sources
    type: constant
    parameters:
      value: [[1.0]]
  - name: Step
    category: sources
    type: step
    parameters:
      value_before: [[0.0]]
      value_after: [[1.0]]
      start_time: 1.0
  connections:
  - name: c1
    ports:
    - Constant.out
    - Algebraic Function.u1
  - name: c2
    ports:
    - Step.out
    - Algebraic Function.u2
gui:
  layout:
    blocks:
      Algebraic Function:
        x: 0.0
        y: 0.0
        orientation: normal
        width: 120.0
        height: 60.0
      Constant:
        x: -197.0
        y: -35.0
        orientation: normal
        width: 120.0
        height: 60.0
      Step:
        x: -196.0
        y: 43.0
        orientation: normal
        width: 120.0
        height: 60.0
