simulation:
  dt: 0.05
  T: 30.0
  solver: fixed
blocks:
  v:
    initial_state: 5.0
    method: euler forward
  x:
    initial_state: 2.0
    method: euler forward
  Sum:
    signs: --
  damping:
    gain: 0.5
    multiplication: Element wise (K * u)
  stiffness:
    gain: 2.0
    multiplication: Element wise (K * u)
logging:
- v.outputs.out
- x.outputs.out
plots:
- title: Position and Velocity
  signals:
  - v.outputs.out
  - x.outputs.out
