schema_version: 1
project:
  name: gui
  metadata:
    created_by: pySimBlocks
    created_at: '2026-02-18T00:00:00Z'
simulation:
  dt: 0.05
  T: 30.0
  solver: fixed
  logging:
  - noise.outputs.out
  - filtered.outputs.out
  plots:
  - title: Noisy signal vs Filtered
    signals:
    - noise.outputs.out
    - filtered.outputs.out
diagram:
  blocks:
  - name: noise
    category: sources
    type: white_noise
    parameters:
      std: 1.0
  - name: alpha
    category: operators
    type: gain
    parameters:
      gain: 0.1
      multiplication: Element wise (K * u)
  - name: filtered
    category: operators
    type: sum
    parameters:
      signs: ++
  - name: Delay
    category: operators
    type: delay
    parameters:
      num_delays: 1
  - name: 1-alpha
    category: operators
    type: gain
    parameters:
      gain: 0.9
      multiplication: Element wise (K * u)
  connections:
  - name: c1
    ports:
    - filtered.out
    - Delay.in
  - name: c2
    ports:
    - noise.out
    - alpha.in
  - name: c3
    ports:
    - 1-alpha.out
    - filtered.in2
  - name: c4
    ports:
    - alpha.out
    - filtered.in1
  - name: c5
    ports:
    - Delay.out
    - 1-alpha.in
gui:
  layout:
    blocks:
      noise:
        x: -1105.0
        y: -385.0
        orientation: normal
        width: 150.0
        height: 60.0
      alpha:
        x: -895.0
        y: -385.0
        orientation: normal
        width: 120.0
        height: 60.0
      filtered:
        x: -670.0
        y: -375.0
        orientation: normal
        width: 120.0
        height: 60.0
      Delay:
        x: -490.0
        y: -365.0
        orientation: normal
        width: 120.0
        height: 60.0
      1-alpha:
        x: -895.0
        y: -310.0
        orientation: normal
        width: 120.0
        height: 60.0
    connections:
      c5:
        route: [[-355.0, -335.0], [-347.0, -335.0], [-347.0, -215.0], [-909.0, -215.0],
          [-909.0, -280.0], [-901.0, -280.0]]
