# ******************************************************************************
#                                  pySimBlocks
#                     Copyright (c) 2026 Université de Lille & INRIA
# ******************************************************************************
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# ******************************************************************************

from __future__ import annotations

from pathlib import Path


SCENE_TEMPLATE = '''\
"""SOFA scene template generated by `pysimblocks sofa-init`.

Run standalone:
    runSofa {name}_scene.py --argv --project-yaml,path/to/project.yaml

Run via pySimBlocks (GUI or CLI): the --project-yaml value is injected
automatically through --argv, no manual flag needed.
"""
import sys, argparse


def createScene(rootnode):
    parser = argparse.ArgumentParser(prog=sys.argv[0])
    parser.add_argument("--project-yaml", type=str, default=None, dest="project_yaml")
    args, _ = parser.parse_known_args()

    # TODO: build your SOFA scene graph here

    # Instantiate your controller and add it to the scene graph
    from {name}_controller import {class_name}Controller
    controller = {class_name}Controller(
        rootnode,
        # TODO: add your own constructor arguments here
        project_yaml=args.project_yaml,
    )
    rootnode.addObject(controller)

    return rootnode, controller
'''

CONTROLLER_TEMPLATE = '''\
"""SOFA controller template generated by `pysimblocks sofa-init`.
"""
from pathlib import Path

from pySimBlocks.blocks.systems.sofa import SofaPysimBlocksController

BASE_DIR = Path(__file__).resolve().parent


class {class_name}Controller(SofaPysimBlocksController):

    def __init__(self, root, project_yaml=None, name="{class_name}Controller"):
        project_yaml = project_yaml or str((BASE_DIR / "project.yaml").resolve())

        # You can modify the project_yaml in case it is None, e.g no argument
        # is passed => default to a project.yaml
        super().__init__(project_yaml=project_yaml, name=name)

        self.root = root
        self.inputs = {{}}   # TODO: e.g. {{"u": np.zeros((n, 1))}}
        self.outputs = {{}}  # TODO: e.g. {{"y": np.zeros((m, 1))}}

    def set_inputs(self):
        raise NotImplementedError("TODO: apply self.inputs to your SOFA scene")

    def get_outputs(self):
        raise NotImplementedError("TODO: read your SOFA scene into self.outputs")
'''


def _to_class_name(name: str) -> str:
    """Convert a snake_case or kebab-case name to PascalCase."""
    parts = name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts if p)


def generate_sofa_scaffold(
    name: str,
    output_dir: Path | str | None = None,
    force: bool = False,
) -> tuple[Path, Path]:
    """Generate a starter SOFA scene + controller pair.

    Writes ``<name>_scene.py`` and ``<name>_controller.py`` pre-filled with
    the ``--project-yaml`` argument parsing and the correct
    ``super().__init__()`` ordering, so new SOFA controllers work correctly
    both standalone (``runSofa``) and when driven by pySimBlocks.

    Args:
        name: Base name used for the generated files and the controller
            class (e.g. ``"finger"`` -> ``finger_scene.py``,
            ``finger_controller.py``, class ``FingerController``).
        output_dir: Directory to write the files into. Defaults to the
            current working directory.
        force: If True, overwrite existing files. Otherwise raises if either
            target file already exists.

    Returns:
        Tuple of (scene_path, controller_path) for the generated files.

    Raises:
        FileExistsError: If a target file already exists and force is False.
    """
    output_dir = Path(output_dir).resolve() if output_dir else Path.cwd()
    output_dir.mkdir(parents=True, exist_ok=True)

    class_name = _to_class_name(name)
    scene_path = output_dir / f"{name}_scene.py"
    controller_path = output_dir / f"{name}_controller.py"

    if not force:
        existing = [p for p in (scene_path, controller_path) if p.exists()]
        if existing:
            raise FileExistsError(
                f"File(s) already exist: {', '.join(str(p) for p in existing)}. "
                "Use force=True to overwrite."
            )

    scene_path.write_text(SCENE_TEMPLATE.format(name=name, class_name=class_name))
    controller_path.write_text(CONTROLLER_TEMPLATE.format(class_name=class_name))

    print(f"[pySimBlocks] Generated {scene_path}")
    print(f"[pySimBlocks] Generated {controller_path}")

    return scene_path, controller_path
