blocks:
- name: ramp
  from: sources
  type: ramp
  slope: [[10.0]]
  start_time: 10
  offset: [[10.0]]
- name: rate_limiter
  from: operators
  type: rate_limiter
  rising_slope: 7.90634
  falling_slope: -1
  initial_output: [[0.0]]
- name: dead_zone
  from: operators
  type: dead_zone
  lower_bound: -0.5
  upper_bound: 0.3
- name: sinusoidal
  from: sources
  type: sinusoidal
  amplitude: 1.0
  frequency: 3.0
connections:
- [ramp.out, rate_limiter.in]
- [sinusoidal.out, dead_zone.in]
simulation:
  dt: 0.016666666666666666
  T: 0.5
  log:
  - ramp.outputs.out
  - rate_limiter.outputs.out
  - dead_zone.outputs.out
  - sinusoidal.outputs.out
plot:
- title: Rate
  log:
  - ramp.outputs.out
  - rate_limiter.outputs.out
- title: Dead Zone
  log:
  - sinusoidal.outputs.out
  - dead_zone.outputs.out
