schema_version: 1
project:
  name: tutorial_2_gui
  metadata:
    created_by: pySimBlocks
    created_at: '2026-02-18T00:00:00Z'
simulation:
  dt: 0.1
  T: 10.0
  solver: fixed
  logging: []
  plots: []
diagram:
  blocks:
  - name: LinearStateSpace
    category: systems
    type: linear_state_space
    parameters:
      A: [[0.99]]
      B: [[1.0]]
      C: [[1.0]]
  connections: []
gui:
  layout:
    blocks:
      LinearStateSpace:
        x: -51.0
        y: -73.0
        orientation: normal
        width: 120.0
        height: 60.0
