schema_version: 1

project:
  name: sofa_exchange
  metadata:
    created_by: pySimBlocks
    created_at: "2026-02-18T00:00:00Z"

simulation:
  dt: 0.01
  T: 5.0
  solver: fixed
  logging:
    - sofa.outputs.measure
    - ref.outputs.out
    - PID.outputs.u
  plots:
    - title: Outputs
      signals:
        - sofa.outputs.measure
        - ref.outputs.out
    - title: Command
      signals:
        - PID.outputs.u

diagram:
  blocks:
    - name: error
      category: operators
      type: sum
      parameters:
        signs: +-
    - name: sofa
      category: systems
      type: sofa_exchange_i_o
      parameters:
        scene_file: ../finger/Finger.py
        input_keys:
          - cable
        output_keys:
          - tip
          - measure
        slider_params:
          ref.value: [-10.0, 50.0]
          PID.Kp: [0.01, 3.0]
          PID.Ki: [0.01, 3.0]
          PID.Kd: [0.001, 0.01]
    - name: ref
      category: sources
      type: constant
      parameters:
        value: [[1.0]]
    - name: PID
      category: controllers
      type: pid
      parameters:
        controller: PID
        Kp: [[0.5]]
        Ki: [[0.8]]
        Kd: [[0.005]]
        integration_method: euler forward
  connections:
    - name: c1
      ports: [sofa.measure, error.in2]
    - name: c2
      ports: [error.out, PID.e]
    - name: c3
      ports: [ref.out, error.in1]
    - name: c4
      ports: [PID.u, sofa.cable]

gui:
  layout:
    blocks:
      error:
        x: 95.0
        y: -5.0
        orientation: normal
        width: 120.0
        height: 60.0
      sofa:
        x: 460.0
        y: -5.0
        orientation: normal
        width: 120.0
        height: 60.0
      ref:
        x: -100.0
        y: -15.0
        orientation: normal
        width: 120.0
        height: 60.0
      PID:
        x: 280.0
        y: -5.0
        orientation: normal
        width: 120.0
        height: 60.0
