schema_version: 1
project:
  name: sofa_plant
  metadata:
    created_by: pySimBlocks
    created_at: '2026-02-18T00:00:00Z'
simulation:
  dt: 0.01
  T: 5.0
  solver: fixed
  logging:
  - sum.outputs.out
  - sofa.outputs.measure
  - ref.outputs.out
  plots:
  - title: Outputs
    signals:
    - sofa.outputs.measure
    - ref.outputs.out
  - title: Command
    signals:
    - sum.outputs.out
diagram:
  blocks:
  - name: error
    category: operators
    type: sum
    parameters:
      signs: +-
  - name: Kp
    category: operators
    type: gain
    parameters:
      gain: [[0.5]]
      multiplication: Element wise (K * u)
  - name: Ki
    category: operators
    type: gain
    parameters:
      gain: [[0.8]]
      multiplication: Element wise (K * u)
  - name: integrator
    category: operators
    type: discrete_integrator
    parameters:
      initial_state: [[0.0]]
      method: euler forward
  - name: sum
    category: operators
    type: sum
    parameters:
      signs: ++
  - name: sofa
    category: systems
    type: sofa_plant
    parameters:
      scene_file: ../finger/Finger.py
      input_keys:
      - cable
      output_keys:
      - tip
      - measure
      slider_params:
        ref.value:
        - -10.0
        - 50.0
        Kp.gain:
        - 0.01
        - 3.0
        Ki.gain:
        - 0.01
        - 3.0
  - name: ref
    category: sources
    type: constant
    parameters:
      value: [[1.0]]
  connections:
  - name: c1
    ports:
    - error.out
    - Kp.in
  - name: c2
    ports:
    - error.out
    - integrator.in
  - name: c3
    ports:
    - Kp.out
    - sum.in1
  - name: c4
    ports:
    - Ki.out
    - sum.in2
  - name: c5
    ports:
    - sum.out
    - sofa.cable
  - name: c6
    ports:
    - sofa.measure
    - error.in2
  - name: c7
    ports:
    - ref.out
    - error.in1
  - name: c8
    ports:
    - integrator.out
    - Ki.in
gui:
  layout:
    blocks:
      error:
        x: -245.0
        y: -35.0
        orientation: normal
        width: 120.0
        height: 60.0
      Kp:
        x: -30.0
        y: -85.0
        orientation: normal
        width: 120.0
        height: 60.0
      Ki:
        x: 140.0
        y: 5.0
        orientation: normal
        width: 120.0
        height: 60.0
      integrator:
        x: -35.0
        y: 5.0
        orientation: normal
        width: 120.0
        height: 60.0
      sum:
        x: 300.0
        y: -75.0
        orientation: normal
        width: 120.0
        height: 60.0
      sofa:
        x: 490.0
        y: -75.0
        orientation: normal
        width: 120.0
        height: 60.0
      ref:
        x: -420.0
        y: -45.0
        orientation: normal
        width: 120.0
        height: 60.0
    connections:
      c1:
        route: [[-110.0, -5.0], [-102.0, -5.0], [-75.0, -5.0], [-75.0, -55.0], [-44.0,
            -55.0], [-36.0, -55.0]]
      c6:
        route: [[625.0, -35.0], [633.0, -35.0], [633.0, 100.0], [-259.0, 100.0], [
            -259.0, 5.0], [-251.0, 5.0]]
