schema_version: 1

project:
  name: file_sources
  metadata:
    created_by: pySimBlocks
    created_at: "2026-02-18T00:00:00Z"

simulation:
  dt: 0.05
  T: 10.0
  solver: fixed
  clock: internal
  logging:
    - npz.outputs.out
    - npy.outputs.out
    - csv.outputs.out
  plots: []

diagram:
  blocks:
    - name: npz
      category: sources
      type: file_source
      parameters:
        file_path: data.npz
        key: y
        repeat: 'False'
        use_time: 'True'
    - name: npy
      category: sources
      type: file_source
      parameters:
        file_path: data.npy
        repeat: 'True'
    - name: csv
      category: sources
      type: file_source
      parameters:
        file_path: data.csv
        key: y
        repeat: 'False'
        use_time: false
  connections: []

gui:
  layout:
    blocks:
      npz:
        x: -305.0
        y: -59.0
        orientation: normal
        width: 120.0
        height: 60.0
      npy:
        x: -300.0
        y: 15.0
        orientation: normal
        width: 120.0
        height: 60.0
      csv:
        x: -295.0
        y: 95.0
        orientation: normal
        width: 120.0
        height: 60.0
