simulation:
  dt: 0.01
  T: 5.0
  solver: fixed
blocks:
  error:
    signs: +-
  sofa:
    scene_file: Finger.py
    input_keys:
    - cable
    output_keys:
    - tip
    - measure
    slider_params:
      ref.value:
      - -10.0
      - 50.0
      PID.Kp:
      - 0.0
      - 20.0
      PID.Ki:
      - 0.0
      - 20.0
  ref:
    value: [[1.0]]
  PID:
    controller: PI
    Kp: [[0.5]]
    Ki: [[0.8]]
    Kd: 0.0
    integration_method: euler forward
logging:
- sofa.outputs.measure
plots:
- title: Outputs
  signals:
  - sofa.outputs.measure
  - ref.outputs.out
- title: Command
  signals:
  - PID.outputs.u
